import 'package:flutter/material.dart';

/// Every icon a category can use, keyed by a stable string stored in
/// Firestore. Icons are looked up through this fixed map — never
/// reconstructed from a stored int — so Flutter's icon tree-shaking can see
/// every icon this app actually uses and keep exactly those glyphs in
/// release builds. Keys are never renamed or removed: categories already
/// saved with them must keep their icon.
const categoryIconsByKey = <String, IconData>{
  'category': Icons.category,
  'restaurant': Icons.restaurant,
  'directions_car': Icons.directions_car,
  'shopping_bag': Icons.shopping_bag,
  'receipt_long': Icons.receipt_long,
  'movie': Icons.movie,
  'favorite': Icons.favorite,
  'school': Icons.school,
  'fastfood': Icons.fastfood,
  'local_hospital': Icons.local_hospital,
  'flight': Icons.flight,
  'home': Icons.home,
  'pets': Icons.pets,
  'fitness_center': Icons.fitness_center,
  'card_giftcard': Icons.card_giftcard,
  'smartphone': Icons.smartphone,
  'content_cut': Icons.content_cut,
  'directions_run': Icons.directions_run,
  'people': Icons.people,
  'directions_bus': Icons.directions_bus,
  'checkroom': Icons.checkroom,
  'wine_bar': Icons.wine_bar,
  'smoking_rooms': Icons.smoking_rooms,
  'computer': Icons.computer,
  'build': Icons.build,
  'house': Icons.house,
  'weekend': Icons.weekend,
  'volunteer_activism': Icons.volunteer_activism,
  'casino': Icons.casino,
  'cookie': Icons.cookie,
  'child_care': Icons.child_care,
  'eco': Icons.eco,
  'shopping_basket': Icons.shopping_basket,
  'work': Icons.work,
  'trending_up': Icons.trending_up,
  'handshake': Icons.handshake,
  'emoji_events': Icons.emoji_events,
  'paid': Icons.paid,

  // Added in 1.8.5.
  'local_cafe': Icons.local_cafe,
  'emoji_food_beverage': Icons.emoji_food_beverage,
  'local_pizza': Icons.local_pizza,
  'lunch_dining': Icons.lunch_dining,
  'ramen_dining': Icons.ramen_dining,
  'rice_bowl': Icons.rice_bowl,
  'kebab_dining': Icons.kebab_dining,
  'bakery_dining': Icons.bakery_dining,
  'icecream': Icons.icecream,
  'cake': Icons.cake,
  'local_drink': Icons.local_drink,
  'set_meal': Icons.set_meal,
  'egg': Icons.egg,
  'shopping_cart': Icons.shopping_cart,
  'local_grocery_store': Icons.local_grocery_store,
  'storefront': Icons.storefront,
  'local_mall': Icons.local_mall,
  'diamond': Icons.diamond,
  'watch': Icons.watch,
  'sell': Icons.sell,
  'dry_cleaning': Icons.dry_cleaning,
  'two_wheeler': Icons.two_wheeler,
  'local_taxi': Icons.local_taxi,
  'electric_rickshaw': Icons.electric_rickshaw,
  'local_gas_station': Icons.local_gas_station,
  'train': Icons.train,
  'pedal_bike': Icons.pedal_bike,
  'local_parking': Icons.local_parking,
  'car_repair': Icons.car_repair,
  'local_shipping': Icons.local_shipping,
  'bolt': Icons.bolt,
  'water_drop': Icons.water_drop,
  'propane_tank': Icons.propane_tank,
  'wifi': Icons.wifi,
  'sim_card': Icons.sim_card,
  'tv': Icons.tv,
  'key': Icons.key,
  'apartment': Icons.apartment,
  'cleaning_services': Icons.cleaning_services,
  'local_laundry_service': Icons.local_laundry_service,
  'kitchen': Icons.kitchen,
  'bed': Icons.bed,
  'lightbulb': Icons.lightbulb,
  'plumbing': Icons.plumbing,
  'medication': Icons.medication,
  'healing': Icons.healing,
  'vaccines': Icons.vaccines,
  'monitor_heart': Icons.monitor_heart,
  'spa': Icons.spa,
  'face': Icons.face,
  'visibility': Icons.visibility,
  'family_restroom': Icons.family_restroom,
  'elderly': Icons.elderly,
  'child_friendly': Icons.child_friendly,
  'celebration': Icons.celebration,
  'mosque': Icons.mosque,
  'menu_book': Icons.menu_book,
  'auto_stories': Icons.auto_stories,
  'edit': Icons.edit,
  'science': Icons.science,
  'business_center': Icons.business_center,
  'print': Icons.print,
  'devices': Icons.devices,
  'sports_esports': Icons.sports_esports,
  'sports_cricket': Icons.sports_cricket,
  'sports_soccer': Icons.sports_soccer,
  'music_note': Icons.music_note,
  'headphones': Icons.headphones,
  'local_activity': Icons.local_activity,
  'subscriptions': Icons.subscriptions,
  'beach_access': Icons.beach_access,
  'hotel': Icons.hotel,
  'luggage': Icons.luggage,
  'camera_alt': Icons.camera_alt,
  'park': Icons.park,
  'savings': Icons.savings,
  'account_balance': Icons.account_balance,
  'account_balance_wallet': Icons.account_balance_wallet,
  'credit_card': Icons.credit_card,
  'payments': Icons.payments,
  'currency_exchange': Icons.currency_exchange,
  'request_quote': Icons.request_quote,
  'percent': Icons.percent,
  'receipt': Icons.receipt,
  'security': Icons.security,
  'gavel': Icons.gavel,
  'local_post_office': Icons.local_post_office,

  // Legacy key: Fruits was first seeded with Icons.apple, which is Apple's
  // brand logo rather than a fruit. Kept so categories already stored under
  // this key show the basket instead; listed last so [keyForIcon] resolves
  // the basket to 'shopping_basket' when such a category is re-saved.
  'apple': Icons.shopping_basket,
};

/// A labelled section of the icon picker.
class CategoryIconGroup {
  final String label;
  final List<String> keys;

  const CategoryIconGroup(this.label, this.keys);
}

/// The icon picker's sections, in order. Every key in [categoryIconsByKey]
/// except the legacy 'apple' appears exactly once (a test checks this).
const categoryIconGroups = [
  CategoryIconGroup('General', ['category', 'favorite', 'emoji_events']),
  CategoryIconGroup('Food & drink', [
    'restaurant',
    'fastfood',
    'lunch_dining',
    'local_pizza',
    'ramen_dining',
    'rice_bowl',
    'kebab_dining',
    'set_meal',
    'bakery_dining',
    'egg',
    'cookie',
    'cake',
    'icecream',
    'local_cafe',
    'emoji_food_beverage',
    'local_drink',
    'wine_bar',
  ]),
  CategoryIconGroup('Groceries & shopping', [
    'shopping_basket',
    'shopping_cart',
    'local_grocery_store',
    'eco',
    'shopping_bag',
    'local_mall',
    'storefront',
    'checkroom',
    'dry_cleaning',
    'diamond',
    'watch',
    'sell',
  ]),
  CategoryIconGroup('Transport', [
    'directions_car',
    'two_wheeler',
    'electric_rickshaw',
    'local_taxi',
    'directions_bus',
    'train',
    'pedal_bike',
    'local_gas_station',
    'local_parking',
    'car_repair',
    'flight',
    'local_shipping',
  ]),
  CategoryIconGroup('Bills & home', [
    'home',
    'house',
    'apartment',
    'key',
    'bolt',
    'water_drop',
    'propane_tank',
    'wifi',
    'smartphone',
    'sim_card',
    'tv',
    'receipt_long',
    'lightbulb',
    'weekend',
    'bed',
    'kitchen',
    'cleaning_services',
    'local_laundry_service',
    'plumbing',
    'build',
  ]),
  CategoryIconGroup('Health & care', [
    'local_hospital',
    'medication',
    'healing',
    'vaccines',
    'monitor_heart',
    'visibility',
    'fitness_center',
    'directions_run',
    'spa',
    'content_cut',
    'face',
  ]),
  CategoryIconGroup('Family & giving', [
    'people',
    'family_restroom',
    'child_care',
    'child_friendly',
    'elderly',
    'pets',
    'card_giftcard',
    'celebration',
    'volunteer_activism',
    'mosque',
  ]),
  CategoryIconGroup('Education & work', [
    'school',
    'menu_book',
    'auto_stories',
    'edit',
    'science',
    'work',
    'business_center',
    'computer',
    'devices',
    'print',
    'local_post_office',
  ]),
  CategoryIconGroup('Fun & travel', [
    'movie',
    'sports_esports',
    'sports_cricket',
    'sports_soccer',
    'music_note',
    'headphones',
    'local_activity',
    'subscriptions',
    'camera_alt',
    'park',
    'beach_access',
    'hotel',
    'luggage',
    'casino',
    'smoking_rooms',
  ]),
  CategoryIconGroup('Money', [
    'paid',
    'payments',
    'account_balance_wallet',
    'account_balance',
    'credit_card',
    'savings',
    'handshake',
    'currency_exchange',
    'request_quote',
    'receipt',
    'percent',
    'trending_up',
    'security',
    'gavel',
  ]),
];

const defaultCategoryIconKey = 'category';

IconData iconForKey(String key) =>
    categoryIconsByKey[key] ?? categoryIconsByKey[defaultCategoryIconKey]!;

String keyForIcon(IconData icon) {
  for (final entry in categoryIconsByKey.entries) {
    if (entry.value == icon) return entry.key;
  }
  return defaultCategoryIconKey;
}
