// Generated by hand from android/app/google-services.json.
// Re-run `flutterfire configure` later to regenerate this file properly and
// add support for other platforms (web, iOS, etc.).

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run flutterfire configure to add web support.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform - '
          'run flutterfire configure to add support.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBahwf18uYshZN2YJ_5Bq3vZuJXQ4mteSI',
    appId: '1:720765164093:android:5dc5b67bf12bc8635e6854',
    messagingSenderId: '720765164093',
    projectId: 'monthly-traq',
    storageBucket: 'monthly-traq.firebasestorage.app',
  );
}
